[package]
name = "interface"
version = "0.1.0"
authors = ["TheSpiritXIII <thespiritxiii@gmail.com>"]

[dependencies]
libloading = "0.3"
notify = "4.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
