[package]
name = "runner"
version = "0.1.0"
authors = ["TheSpiritXIII <thespiritxiii@gmail.com>"]

[dependencies]
chrono = "0.3"
libloading = "0.4"
notify = "4.0"
sdl2 = " 0.30.0-beta"

[dependencies.interface]
path = "../interface"

[dependencies.engine]
path = "../engine"
